### ISSUE TITLE
"outlineColor" is not a valid style property

### ISSUE THREAD

**Issue by yunau** [marcocesarato/react-native-input-validator#3]
outlineColor: "transparent" needs to be removed in style.jsj file.

**Comment by yunau** [comment]
input: {
        flex: 1,
        minHeight: 50,
        borderColor: '#FFF',
        borderBottomColor: '#CCC',
        backgroundColor: 'transparent',
        justifyContent: 'center',
        borderWidth: 1,
        color: 'black',
        fontSize: 20,
        borderRadius: 4,
        marginTop: 20,
        //outlineColor: "transparent". --> need to be removed
    },

**Comment by marcocesarato** [comment]
Done. Now should be fine on version 1.0.10. Thank you for your feedback
